### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by eduardagoulart** [eduardagoulart/secomp#3]
Como fazer um Hello World em Django, mostrando o Django Admin

**Comment by khdc-me** [comment]
Apareciste entre los resultados mientras busacaba proyectos de Django en los cuales puedo contribuir.

Parece que estás queriendo aprender, felicidades. Te invito a un [grupo slack de pythonistas](https://pyslackers.com/slack/) (hay ya varias personas de Brasil). Hay canales para python, django, web-dev, y muchos más temas.

Éxito.
